---

- name: Invoke Job Template in response to MQTT Messages
  hosts: all

  sources:
    - kubealex.eda.mqtt:
        host: "{{ mqtt_host }}"
        port: "{{ mqtt_port }}"
        topic: "{{ mqtt_topic }}"

  rules:
    - name: Run 'Scale Up K8s Service' Template
      condition: event.action is defined
      action:
        run_job_template:
          name: "{{ job_template_name }}"
          organization: Default
