---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapp

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: basic-config
    files:
      - files/nginx-basic.conf

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml

