---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eda-postgres-15-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: eda-postgres-volume
  hostPath:
    path: /data/eda/postgres-15
